"""Regenerate results/REPORT.md from the ledger. Claims are written by hand."""

from pathlib import Path

from loopgraph import Ledger, Objective, pareto_front
from loopgraph.report import table

R = Path(__file__).resolve().parents[1] / "results"
L = Ledger(R / "ledger.jsonl")
from wormstage.data import load  # noqa: E402

dev = L.entries("develop")
rest = [e for e in dev if e.params["stimulus"] == "none"]
ash = [e for e in dev if e.params["stimulus"] == "ASH"]
for e in dev:
    s = load(e.params["stage"])
    e.params["age"] = f"{s.label} {s.hours}h" if s.hours is not None else "adult (Cook 2019)"
    e.params["synapses"] = int(s.chemical.sum())

design = L.entries("design_witvliet8")
front = sorted(pareto_front(design, [Objective("forward_bl_s"), Objective("servos", False)]),
               key=lambda e: e.metrics["servos"])

out = ["# wormstage results", "", "Generated by `scripts/report.py` from `ledger.jsonl`.", "",
       "## Development: the same robot, driven by each stage's circuit", "",
       "Robot: 12 links, compliant joints, agar-like drag (K = 40). ASH columns: the nerve ring "
       "of that stage is stimulated at ASH; the robot reverses if the backward command "
       "interneurons are driven harder than the forward ones. p is against 1000 "
       "degree-preserving shuffles of that stage's own wiring (glutamate taken as excitatory).", "",
       "| stage | age | synapses | rest: forward BL/s | rest: freq Hz | ASH reversal index | p (shuffled) | ASH: robot BL/s | bit-exact |",
       "|---|---|---|---|---|---|---|---|---|"]
for r, a in zip(rest, ash):
    out.append(f"| {r.params['stage']} | {r.params['age']} | {r.params['synapses']} | "
               f"{r.metrics['forward_bl_s']:.3f} | {r.metrics['freq_hz']:.2f} | "
               f"{a.metrics['reversal_index']:+.3f} | {a.metrics['brain_p']:.3f} | "
               f"{a.metrics['forward_bl_s']:+.3f} | {a.metrics.get('bit_exact')} |")
out += ["", "## L1 extrasynaptic ventral drive (Lu et al. 2022) ablated", "",
        table(sorted(L.entries("ablate_tonic"), key=lambda e: (e.params["K"], e.params["ventral_tonic"])),
              ["K", "ventral_tonic"], ["undulating", "forward_bl_s", "symmetry", "freq_hz"],
              ["drag K", "ventral drive", "undulating", "forward BL/s", "symmetry", "freq Hz"]),
        "", "## Medium: water-like (K 1.5) to agar-like (K 40)", "",
        table(L.entries("medium"), ["stage", "K"],
              ["freq_hz", "wavelength_bl", "forward_bl_s", "symmetry"],
              ["stage", "K", "freq Hz", "wavelength (body lengths)", "forward BL/s", "symmetry"]),
        "", "## Design: fewest servos that keep the adult gait", "",
        "Gates: coherent travelling wave, symmetry >= 0.7, bit-exact C. Pareto frontier of "
        f"{len(design)} agent-proposed designs ({sum(e.admitted for e in design)} admitted):", "",
        table(front, ["n_links", "field", "w_sr", "k_joint"],
              ["servos", "forward_bl_s", "freq_hz", "symmetry"],
              ["links", "receptive field", "stretch gain", "joint stiffness", "servos",
               "forward BL/s", "freq Hz", "symmetry"])]
(R / "REPORT.md").write_text("\n".join(out) + "\n")
print((R / "REPORT.md").read_text())
