"""Emit a compiled motor circuit as freestanding C99, and check it bit-exact.

The emitted `worm_tick` is the same integer program as `circuit.tick`: joint
readings in mrad in, joint targets in mrad out, state in a caller-owned
struct. No malloc, no floats, no libc.
"""

from __future__ import annotations

import numpy as np

from loopgraph.cgate import compile_and_run

from .circuit import OFF, ON, Q12, Q15, Compiled, State, reset, tick


def _arr(t: str, name: str, v) -> str:
    v = [int(x) for x in np.asarray(v).ravel()] or [0]
    return f"static const {t} {name}[{len(v)}] = {{{', '.join(map(str, v))}}};\n"


def _fields(fields) -> tuple[list[int], list[int]]:
    idx, off = [], [0]
    for f in fields:
        idx += [int(i) for i in f]
        off.append(len(idx))
    return idx, off


def emit(k: Compiled, name: str = "worm") -> dict[str, str]:
    J, nD, nV = k.n_joints, len(k.dorsal_pos), len(k.ventral_pos)
    up = name.upper()
    di, do = _fields(k.d_field)
    vi, vo = _fields(k.v_field)
    h = f"""/* Generated by wormstage ({k.stage} circuit). Do not edit. */
#ifndef {up}_CIRCUIT_H
#define {up}_CIRCUIT_H
#include <stdint.h>

#define {up}_JOINTS {J}
#define {up}_ND {nD}
#define {up}_NV {max(nV, 1)}

typedef struct {{
    int8_t s_d[{up}_ND], s_v[{up}_NV];
    int32_t m_d[{up}_JOINTS], m_v[{up}_JOINTS];
}} {name}_state_t;

void {name}_reset({name}_state_t *s);
/* phi: joint readings, mrad. target: joint commands, mrad. */
void {name}_tick({name}_state_t *s, const int16_t phi[{up}_JOINTS], int16_t target[{up}_JOINTS]);

#endif
"""
    c = [f"/* Generated by wormstage. Do not edit. */\n#include \"{name}.h\"\n\n",
         _arr("int16_t", "D_IDX", di), _arr("int16_t", "D_OFF", do),
         _arr("int32_t", "D_GAIN", k.d_gain), _arr("int16_t", "J_D", k.j_dorsal),
         _arr("int32_t", "NMJ", k.nmj)]
    if nV:
        c += [_arr("int16_t", "V_IDX", vi), _arr("int16_t", "V_OFF", vo),
              _arr("int32_t", "V_GAIN", k.v_gain), _arr("int16_t", "J_V", k.j_ventral),
              _arr("int16_t", "V_CROSS", k.v_cross)]
    s0 = reset(k)
    c.append(f"""
static int8_t sw(int8_t s, int32_t i)
{{
    return i > {ON} ? 1 : (i < {OFF} ? 0 : s);
}}

static int32_t stretch(const int16_t *phi, const int16_t *idx, int a, int b, int32_t g, int sign)
{{
    int32_t sum = 0;
    for (int i = a; i < b; ++i) sum += phi[idx[i]];
    return (int32_t)(((int64_t)(sign * sum) * g) >> 16);
}}

void {name}_reset({name}_state_t *s)
{{
    for (int i = 0; i < {up}_ND; ++i) s->s_d[i] = {int(s0.s_d[0])} * (i == {int(np.argmax(s0.s_d))});
    for (int i = 0; i < {up}_NV; ++i) s->s_v[i] = 0;
    for (int j = 0; j < {up}_JOINTS; ++j) s->m_d[j] = s->m_v[j] = 0;
}}

void {name}_tick({name}_state_t *s, const int16_t phi[{up}_JOINTS], int16_t target[{up}_JOINTS])
{{
    int8_t nd[{up}_ND];
    for (int n = 0; n < {up}_ND; ++n) {{
        int32_t sd = stretch(phi, D_IDX, D_OFF[n], D_OFF[n + 1], D_GAIN[n], 1);
        nd[n] = sw(s->s_d[n], {k.i_on} + (int32_t)(((int64_t){k.w_sr} * sd) >> 12));
    }}
""")
    if nV:
        c.append(f"""    int8_t nv[{up}_NV];
    for (int n = 0; n < {up}_NV; ++n) {{
        int32_t sv = stretch(phi, V_IDX, V_OFF[n], V_OFF[n + 1], V_GAIN[n], -1);
        int32_t i = {k.i_bias} - {Q12} * nd[V_CROSS[n]] + {k.i_on}
                    + (int32_t)(((int64_t){k.w_sr} * sv) >> 12);
        nv[n] = sw(s->s_v[n], i);
    }}
    for (int n = 0; n < {up}_NV; ++n) s->s_v[n] = nv[n];
""")
    c.append(f"""    for (int n = 0; n < {up}_ND; ++n) s->s_d[n] = nd[n];
    for (int j = 0; j < {up}_JOINTS; ++j) {{
        int32_t dd = {Q15} * nd[J_D[j]];
""")
    if nV:
        c.append(f"        int32_t dv = {Q15} * s->s_v[J_V[j]];\n")
    else:
        c.append(f"        int32_t dv = {k.tonic} - dd;\n        if (dv < 0) dv = 0;\n")
    c.append(f"""        s->m_d[j] += (int32_t)(((int64_t)(dd - s->m_d[j]) * {k.alpha}) >> 15);
        s->m_v[j] += (int32_t)(((int64_t)(dv - s->m_v[j]) * {k.alpha}) >> 15);
        int64_t t = ((int64_t)(s->m_v[j] - s->m_d[j]) * NMJ[j]) >> 15;
        target[j] = (int16_t)(t > 32767 ? 32767 : (t < -32768 ? -32768 : t));
    }}
}}
""")
    return {f"{name}.h": h, f"{name}.c": "".join(c)}


def check(k: Compiled, phis: np.ndarray, name: str = "worm") -> tuple[bool, int]:
    """Drive C and numpy with the same reading sequence; compare every target."""
    phis = np.asarray(phis, np.int64)
    st: State = reset(k)
    ref = []
    for p in phis:
        st, t = tick(k, st, p)
        ref.append(t)
    ref = np.array(ref)
    up = name.upper()
    main = f"""#include <stdio.h>
#include "{name}.h"
int main(void) {{
    {name}_state_t s;
    int16_t phi[{up}_JOINTS], t[{up}_JOINTS];
    int v;
    {name}_reset(&s);
    for (;;) {{
        for (int j = 0; j < {up}_JOINTS; ++j) {{
            if (scanf("%d", &v) != 1) return 0;
            phi[j] = (int16_t)v;
        }}
        {name}_tick(&s, phi, t);
        for (int j = 0; j < {up}_JOINTS; ++j) printf("%d ", t[j]);
        printf("\\n");
    }}
}}
"""
    stdin = "\n".join(" ".join(map(str, p)) for p in phis) + "\n"
    out = compile_and_run(emit(k, name), main, stdin)
    got = np.array([[int(x) for x in l.split()] for l in out.strip().splitlines()])
    bad = int(np.sum(np.any(got != ref, axis=1)))
    return bad == 0, bad
